name: jiezi_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.8.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  gio: ^0.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.30.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  openapi_gen: ^1.1.0
